version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony_app
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      SYMFONY_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@db:3306/symfony
    networks:
      - symfony

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - symfony

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: symfony_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - symfony

# Networks
networks:
  symfony:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
